name: marketplace_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  appwrite: ^11.0.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  file_picker: ^6.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

